version: "2"
services:
  polonium_server:
    image: rgrannell1/polonium_site

#  polonium_kibana:
#    image: docker.elastic.co/kibana/kibana:6.1.0
#    depends_on:
#      - polonium_elasticsearch
#      - polonium_server
#    environment:
#      - ELASTICSEARCH_URL=http://localhost:9200
#      - server.host=localhost
#      - elasticsearch.username=
#      - elasticsearch.password=

  polonium_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.minimum_master_nodes=1
      - cluster.name=poloinum-logs
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=2gb
      - cluster.routing.allocation.disk.watermark.flood_stage=2gb
      - node.name='primary'
      - node.master=true
      - node.data=true
    ports:
      - 9200:9200
      - 9300:9300
