version: "2"
services:

  polonium_server:
    container_name: polonium_server
    image: rgrannell1/polonium_site
    ports:
      - 80:8080
      - 443:8081

  polonium_elasticsearch:
    container_name: polonium_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.minimum_master_nodes=1
      - cluster.name=polonuim-logs
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=2gb
      - cluster.routing.allocation.disk.watermark.flood_stage=2gb
      - node.name='primary'
      - node.master=true
      - node.data=true
    ports:
      - 9200:9200
      - 9300:9300

  polonium_apm:
    container_name: polonium_apm
    image: docker.elastic.co/apm/apm-server:6.1.1
    links:
      - polonium_elasticsearch
    environment:
    environment:
      ELASTICSEARCH_URL: http://polonium_elasticsearch:9200
    command: apm-server -e -E output.elasticsearch.hosts=$${ELASTICSEARCH_URL}

  polonium_kibana:
    container_name: polonium_kibana
    image: docker.elastic.co/kibana/kibana:6.1.1
    environment:
      ELASTICSEARCH_URL: http://polonium_elasticsearch:9200
    links:
      - polonium_elasticsearch
    ports:
      - 5601:5601
