---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - setup: # aka gather_facts

  tasks:
    - name: Check the VM can be contacted
      action: ping
    - apt_repository:
        repo: 'ppa:certbot/certbot'

    - name: 'Install Certbot'
      apt:
        name: certbot
        state: latest
        update_cache: yes

    - name: Copy Remote Certificates
      synchronize:
        mode: pull
        src: "/etc/letsencrypt/archive/polonium.rgrannell.world/"
        dest: "../../config/credentials/certs/"
        recursive: yes

    - name: Copy Remote Certificates To Dist
      synchronize:
        mode: pull
        src: "/etc/letsencrypt/archive/polonium.rgrannell.world/"
        dest: "../../dist/config/credentials/certs/"
        recursive: yes

- import_playbook: roles/obtain-certificates/tasks/main.yaml
