---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - setup:

  tasks:
    - name: Check the VM can be contacted
      action: ping

    - name: 'Install Docker'
      apt:
        name: docker.io
        state: latest
        update_cache: yes

    - name: 'Copy'
      copy:
        src: ../../dist
        dest: /dist
