---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - setup: # aka gather_facts

  tasks:
    - name: Check the VM can be contacted
      action: ping

    - name: 'Install Pip'
      apt:
        name: python-pip
        update_cache: yes

    - name: 'Install docker-py'
      shell: 'sudo pip install docker-py'

    - name: "Log into Dockerhub"
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        email: "{{ docker_email }}"

    - name: 'Pull Server Image'
      docker_image:
        name: rgrannell1/polonium_site

    - name: 'Run Docker Image'
      docker_container:
        name: polonium_site
        image: rgrannell1/polonium_site:latest
        pull: yes
        state: started
        ports:
          - "80:8080"
          - "443:8081"
